# Generated by Django 6.0.4 on 2026-04-23 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=100)),
                ('primary_crime', models.CharField(choices=[('murder', 'Murder'), ('fraud', 'Fraud'), ('theft', 'Theft'), ('terrorism', 'Terrorism'), ('cybercrime', 'Cybercrime'), ('drug_trafficking', 'Drug Trafficking'), ('kidnapping', 'Kidnapping'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('wanted', 'Wanted'), ('arrested', 'Arrested'), ('released', 'Released')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization_type', models.CharField(choices=[('mafia', 'Mafia'), ('cartel', 'Cartel'), ('gang', 'Gang'), ('terrorist', 'Terrorist Group'), ('cybercrime', 'Cybercrime Network'), ('other', 'Other')], max_length=50)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], default='open', max_length=20)),
                ('description', models.TextField()),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.criminal')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Role in organization (e.g., Leader, Member, Enforcer)', max_length=100)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.criminal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.organization')),
            ],
            options={
                'unique_together': {('criminal', 'organization')},
            },
        ),
    ]
